version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.1.4
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus